"""Shared constants for browser agent."""

ALLOWED_COMMANDS = {
    # Core
    "open",
    "goto",
    "click",
    "dblclick",
    "fill",
    "type",
    "press",
    "select",
    "drag",
    "hover",
    "upload",
    "check",
    "uncheck",
    "snapshot",
    "eval",
    "dialog-accept",
    "dialog-dismiss",
    "resize",
    # Navigation
    "go-back",
    "go-forward",
    "reload",
    # Keyboard
    "keydown",
    "keyup",
    # Mouse
    "mousemove",
    "mousedown",
    "mouseup",
    "mousewheel",
    # Save as
    "screenshot",
    "pdf",
    "close",
    "close-all",
    "kill-all",
    # Tabs
    "tab-list",
    "tab-new",
    "tab-close",
    "tab-select",
    # Sessions
    "list",
    "delete-data",
    # Storage
    "state-save",
    "state-load",
    "cookie-list",
    "cookie-get",
    "cookie-set",
    "cookie-delete",
    "cookie-clear",
    "localstorage-list",
    "localstorage-get",
    "localstorage-set",
    "localstorage-delete",
    "localstorage-clear",
    "sessionstorage-list",
    "sessionstorage-get",
    "sessionstorage-set",
    "sessionstorage-delete",
    "sessionstorage-clear",
    # Network
    "route",
    "route-list",
    "unroute",
    # DevTools
    "console",
    "network",
    "run-code",
    "tracing-start",
    "tracing-stop",
    "video-start",
    "video-stop",
}
